### ISSUE TITLE
Install routine in "Vanilla Spark on your Local Machine" is outdated

### ISSUE THREAD

**Issue by KrisSimon** [data-derp/data-derp.github.io#119]
In the videos there is adoptopenjdk8 mentioned. That package is no longer available in brew. 
The version we have is: 16.0.1. 

- Check if it works with the current version of java
- If so: place a hint on the page.
- If not: update the chapter to work with current versions of java

**Comment by syed-tw** [comment]
<img width="800" alt="Screenshot 2024-02-20 at 10 04 27 AM" src="https://github.com/data-derp/data-derp.github.io/assets/60807649/851d4e35-37b8-4da0-b1e6-95a4e7111a63">

**Comment by syed-tw** [comment]
fixed
