### ISSUE TITLE
Delta Lake Walkthrough - CMD 71: The amount that we are updating is already set to the same amount

### ISSUE THREAD

**Issue by kelseymok** [data-derp/data-derp.github.io#35]

**Comment by syed-tw** [comment]
This is already been taken care in the `delta-lake-walkthrough_updated` file in the git repo. We should just replace `delta-lake-walkthrough` with `delta-lake-walkthrough_updated` in the git repo

**Comment by kelseymok** [comment]
- [ ] Needs PR against delta-lake-walkthrough.py

**Comment by syed-tw** [comment]
Hello @kelseymok The PR is ready for review but it is in `small-exercises` repo so I cannot link it with this issue. Can you please change the repo of this ticket to `small-exercises`. Thanks !

**Comment by kelseymok** [comment]
Just copy paste the link of the PR here :) or mention the link of this issue in the PR. There is some github magic.

**Comment by syed-tw** [comment]
hahaha..I like talking here :D @kelseymok . Here is the [link](https://github.com/data-derp/small-exercises/pull/41)

**Comment by kelseymok** [comment]
merged!
