### ISSUE TITLE
Update summary of Apache Spark

### ISSUE THREAD

**Issue by kelseymok** [data-derp/data-derp.github.io#73]
https://data-derp.github.io/docs/2.0/batch-processing/apache-spark

Order of topics
- [x] Quick 1 paragraph overview of what Apache Spark is and what it does
- [x] Apache Spark Typology (e.g. architecture of nodes, different modes)
- [x] What is a transformation, what is an action? (copy and paste from Spark Shuffling section - just cover example transformations and actions, lazy evaluation. Don't cover shuffling here)
- [x] How are actions and transformations evaluated in Spark (as a distributed system)
- [x] What makes Spark fast and relevant to our data work? (e.g. compared to running workloads as a Java program on Kubernetes - there are certain optimisations that are relevant to Spark and large volumes of data)
- [x] Move overview videos to "More on Spark (Bonus)" (re-evaluate at the time w/ Kelsey at the end)
- [x] Make sure to pull the Useful Links to bottom (mark as bonus)
- [x] Set time estimation (no longer than max 20 minutes, bonus content doesn't count)

**Comment by syed-tw** [comment]
Hello @kelseymok This is complete and comitted to `data-derp\version 2.0`. Please have a look when you get a chance.

**Comment by kelseymok** [comment]
Looks good - also made some minor formatting
