### ISSUE TITLE
[Examples] [Content] Beyond the BatchHandling / Late Data - "sum" might not the best solution for the domain 

### ISSUE THREAD

**Issue by petershaw** [data-derp/data-derp.github.io#92]
In handling-late-data the function `sum` is used in the first examples. Even though this is quite useful to illustrate the functionality, it does not fit into the business domain. 

For my understanding, the examples show the price of a stock market participant. In this case, Apple (AAPL). It is a display app for prices within one minute of a time window. When prices change, the current examples sums it up. 

For example, the price of the paper at 12:01:01 is 1000 dollars. and the price increases to 1010 at 12:01:05 that the `totalPrice` of this paper is not 2010. It can be the max(), but I would rather expect the average price within the minute.  

The current example: 
```
 windowedWords = stocksDF\
     .withWatermark("EventTime", "2 minute") \
     .groupBy(window("EventTime", "1 minute"), stocksDF.symbol)\
     .agg(sum("price").alias("totalPrice"))
```

suggestion: 
```
 windowedWords = stocksDF\
     .withWatermark("EventTime", "2 minute") \
     .groupBy(window("EventTime", "1 minute"), stocksDF.symbol)\
     .agg(avg("price").alias("averagePrice"))
```

Sidenote: the comment is not showing what the function do: 
```
# Group the data by window and word and compute the count of each group
```
suggestion: `Group the data by window and compute the average price`

Discussion: 
The results of `sum` are easy to understand even without much concentration of the reader. `avg` produces an output that is probably not so nice to read ( sum: _1 + 1 = 2_ ). But the correct functional purpose of the application is less distracting when it is avg, max or mean, not sum.

**Comment by kelseymok** [comment]
@syed-tw to check with @petershaw in the evening for a desk check

**Comment by marius-tw** [comment]
Was the decision on this, to keep it for readability purposes at the `sum` being used as aggregation instead of `avg`.

Currently there is still a divergence at 

https://github.com/data-derp/exercise-vanilla-spark/blob/main/src/11%20-%20StreamingTumblingWindow.py

and

https://github.com/data-derp/data-derp.github.io/blob/3f06e06d410a94dfc29a851429062fcfba75f157/versioned_docs/version-2.0/beyond-the-batch/handling-late-data.mdx#L72
