### ISSUE TITLE
Final Charge Time | type error or on purpose?

### ISSUE THREAD

**Issue by petershaw** [data-derp/data-derp.github.io#95]
On cmd 43 in the final charge time the `reservation_id` is incorrectly typed in the schema - should be an Integer instead.
The solutions shows uses an IntegerType() already, but the schema is incorrectly a "string". 

I wonder if this is on purpose, or just a leftover/typo.

**Comment by kelseymok** [comment]
@petershaw @tw-SeanLuckett https://github.com/data-derp/exercise-ev-databricks/commit/1c36cab7e5693d546126a4cad94c335470e5e692 fixed! Let me know if something looks weird still. Thanks for the catch!
