### ISSUE TITLE
Batch Processing - Silver | StartTransaction Request Cast Columns (cmd 30)

### ISSUE THREAD

**Issue by petershaw** [data-derp/data-derp.github.io#96]
In the notebooks there is an import 
```
from pyspark.sql.types import TimestampType
```
`TimestampType` is returned by the to_timestamp function from `pyspark.sql.functions`

In the solution this is fixed. 

To guide to the correct manual it should be in the notebook, too: 

```
from pyspark.sql.functions import to_timestamp
```

**Comment by KrisSimon** [comment]
It's all there: `Hint: You have to import the function from "pyspark.sql.functions" first.`
